services:
  db:
    image: postgres:15-alpine
    container_name: vocabu-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: lingo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d lingo']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
